### ISSUE TITLE
Thread safety and segfaults

### ISSUE THREAD

**Issue by dballard** [struCoder/pidusage#8]
Go hashmaps are sadly not thread safe, so when you have things like 
line 142
```
		history[pid] = *stat
```
it is not safe. My app has different monitors running in different threads, I use this pacakge for cpu and memory monitors, and sometimes they collide and I get 

```

Error:

fatal error: concurrent map writes

goroutine 22 [running]: runtime.throw(0x29c1b6, 0x15)

   /usr/lib/go-1.7/src/runtime/panic.go:566 +0x78 fp=0x10632c58 sp=0x10632c4c

runtime.mapassign1(0x268668, 0x10668880, 0x10632cf8, 0x10632d4c)

   /usr/lib/go-1.7/src/runtime/hashmap.go:458 +0x94 fp=0x10632cd8 sp=0x10632c58

github.com/struCoder/pidusage.stat(0x6c30, 0x298086, 0x4, 0x4, 0x0, 0x0)

   go/src/github.com/struCoder/pidusage/pidusage.go:142 +0xc64 fp=0x10632ebc sp=0x10632cd8

github.com/struCoder/pidusage.wrapper.func1(0x6c30, 0x106688a0, 0x0, 0x0)

   go/src/github.com/struCoder/pidusage/pidusage.go:40 +0x4c fp=0x10632ee0 sp=0x10632ebc

github.com/struCoder/pidusage.GetStat(0x6c30, 0x10632f10, 0x0, 0x0)

   go/src/github.com/struCoder/pidusage/pidusage.go:152 +0x6c fp=0x10632ef8 sp=0x10632ee0

cwtch.im/cwtch/server/metrics.(*Monitors).Start.func3(0x1069ebb8, 0x1066a380)

   go/src/cwtch.im/cwtch/server/metrics/monitors.go:37 +0x28 fp=0x10632f0c sp=0x10632ef8

cwtch.im/cwtch/server/metrics.(*monitorHistory).monitorThread(0x1069e800)

   go/src/cwtch.im/cwtch/server/metrics/metrics.go:218 +0xfc fp=0x10632fcc sp=0x10632f0c

runtime.goexit()
```

This could pretty easily be fixed if you add a global write lock
``` 
	writeLock         sync.Mutex
....
writeLock.Lock()
history[pid] = *stat
writeLock.Unlock()
```

Should fix this issue

**Comment by dballard** [comment]
added a PR #9 to fix this :)

**Comment by struCoder** [comment]
@dballard 
Thanks 👍
